spring:
  application:
    name: logistica
  kafka:
    bootstrap-servers: http://localhost:29092
    consumer:
      group-id: icompras-logistica
      auto-offset-reset: earliest

server:
  port: 8084

icompras:
  config:
    kafka:
      topics:
        pedidos-faturados: icompras.pedidos-faturados
        pedidos-enviados: icompras.pedidos-enviados